/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Arquivo.java
 *
 * Created on 26/05/2011, 20:59:56
 */

package org.motemediacenter.layout;

import java.io.File;
import java.util.Scanner;
import javax.activation.MimetypesFileTypeMap;

/**
 *
 * @author badiale
 */
public class Arquivo extends javax.swing.JPanel {
    private File f;
    private ListaArquivos parent;

    public void setParent(ListaArquivos parent) { this.parent = parent; }

    @Override
    public ListaArquivos getParent() { return this.parent; }

    /** Creates new form Arquivo */
    public Arquivo(File f) {
        initComponents();

        // tipo do arquivo
        String fileTypeName = new MimetypesFileTypeMap().getContentType(f);

        this.f = f;
        lblDescricao.setText(f.getName());
        lblDescricao.setToolTipText(f.getName());
        lblImagem.setText(fileTypeName);
        lblImagem.setToolTipText(fileTypeName);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagem = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();

        lblImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagem.setName("lblImagem"); // NOI18N
        lblImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblImagemMouseReleased(evt);
            }
        });

        lblDescricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescricao.setText("Descrição");
        lblDescricao.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblDescricao.setName("lblDescricao"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDescricao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescricao)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblImagemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagemMouseReleased
        if (f.isDirectory()) {
            ListaArquivos la = this.getParent();
            la.loadPath(f.getAbsolutePath());
        } else {
            try {
                String[] cmd = new String[2];
                // TODO executar o mplayer corretamente
                //cmd[0] = "mplayer";
                //cmd[1] = "-quiet";
                //cmd[2] = "-slave";
                cmd[0] = "xdg-open";
                cmd[1] = f.getPath();
                Process player = Runtime.getRuntime().exec(cmd, null);
                Scanner s = new Scanner (player.getInputStream());
                while (s.hasNextLine()) System.out.println(s.nextLine());
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_lblImagemMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblImagem;
    // End of variables declaration//GEN-END:variables

}
