/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListaArquivos.java
 *
 * Created on 26/05/2011, 20:55:49
 */

package org.motemediacenter.layout;

import java.io.File;
import java.io.FileFilter;
import java.io.PrintStream;

/**
 *
 * @author badiale
 */
public class ListaArquivos extends javax.swing.JPanel {
    private boolean showNavigation;

    /** Creates new form ListaArquivos */
    public ListaArquivos() {
        initComponents();
        setShowNavigation(false);
    }

    // exibe ou na a barra de navegação
    public void setShowNavigation (boolean show) {
        showNavigation = show;
        btnVoltar.setVisible(show);
        btnIr.setVisible(show);
        txtPath.setVisible(show);
    }
    public boolean getShowNavigation() { return this.showNavigation; }

    // add a new file to this panel
    public void addFile (File f) {
        Arquivo arquivo = new Arquivo(this, f);
        arquivo.setVisible(true);

        panFiles.add(arquivo);
    }

    // clean this panel
    public void clear () {
        setVisible(false);
        panFiles.removeAll();
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnIr = new javax.swing.JButton();
        txtPath = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        scrScrollBar = new javax.swing.JScrollPane();
        panFiles = new javax.swing.JPanel();
        btnRolarDireita = new javax.swing.JButton();

        jButton1.setText("jButton1");
        jButton1.setName("jButton1"); // NOI18N

        btnIr.setText("Ir");
        btnIr.setName("btnIr"); // NOI18N
        btnIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrActionPerformed(evt);
            }
        });

        txtPath.setName("txtPath"); // NOI18N

        btnVoltar.setText("Voltar");
        btnVoltar.setName("btnVoltar"); // NOI18N
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jButton3.setText("<");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        scrScrollBar.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrScrollBar.setName("scrScrollBar"); // NOI18N

        panFiles.setName("panFiles"); // NOI18N
        panFiles.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        scrScrollBar.setViewportView(panFiles);

        btnRolarDireita.setText(">");
        btnRolarDireita.setName("btnRolarDireita"); // NOI18N
        btnRolarDireita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRolarDireitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPath, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIr))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrScrollBar, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRolarDireita))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnIr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrScrollBar, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addComponent(btnRolarDireita, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrActionPerformed
        loadPath(txtPath.getText());
}//GEN-LAST:event_btnIrActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        File arquivo = new File(txtPath.getText());
        String pai = arquivo.getParent();
        if (pai != null) {
            loadPath(pai);
            txtPath.setText(pai);
        }
}//GEN-LAST:event_btnVoltarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int value = scrScrollBar.getHorizontalScrollBar().getValue();
        int bloco = scrScrollBar.getHorizontalScrollBar().getBlockIncrement();

        scrScrollBar.getHorizontalScrollBar().setValue(value - 3 * bloco);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnRolarDireitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRolarDireitaActionPerformed
        int value = scrScrollBar.getHorizontalScrollBar().getValue();
        int bloco = scrScrollBar.getHorizontalScrollBar().getBlockIncrement();

        scrScrollBar.getHorizontalScrollBar().setValue(value + 3 * bloco);
    }//GEN-LAST:event_btnRolarDireitaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIr;
    private javax.swing.JButton btnRolarDireita;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel panFiles;
    private javax.swing.JScrollPane scrScrollBar;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables

    // adiciona os arquivos a partir de um caminho
    void loadPath(String path) {
        clear();

        setVisible(false);
        
        File fpath = new File(path);
        if (fpath.exists()) {
            // salva o diretorio atual entre os diretorios recentes
            try {
                File recente_path = new File("resources/configs/path");
                PrintStream out = new PrintStream(recente_path);
                out.println(path);
                out.close();
            } catch (Exception e) { System.err.println("Erro ao salvar path: "+ e.getMessage()); }

            txtPath.setText(fpath.getAbsolutePath());

            // primeiro exibe os diretorios
            File aqui = new File(path);
            File[] arquivos = aqui.listFiles(new FileFilter() {

                public boolean accept(File pathname) {
                    return pathname.isDirectory() && !pathname.isHidden();
                }
            });
            if (arquivos != null)
                for (int i = 0; i < arquivos.length; i++)
                    addFile(arquivos[i]);

            // depois exibe os arquivos
            arquivos = aqui.listFiles(new FileFilter() {

                public boolean accept(File pathname) {
                    return pathname.isFile() && !pathname.isHidden();
                }
            });
            if (arquivos != null)
                for (int i = 0; i < arquivos.length; i++)
                    addFile(arquivos[i]);

            setVisible(true);
        }
    }

}
