/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListaArquivos.java
 *
 * Created on 26/05/2011, 20:55:49
 */

package org.motemediacenter.layout;

import java.io.File;

/**
 *
 * @author badiale
 */
public class ListaArquivos extends javax.swing.JPanel {
    private boolean showNavigation;

    /** Creates new form ListaArquivos */
    public ListaArquivos() {
        initComponents();
        setShowNavigation(false);
    }

    // exibe ou na a barra de navegação
    public void setShowNavigation (boolean show) {
        showNavigation = show;
        btnVoltar.setVisible(show);
        btnIr.setVisible(show);
        txtPath.setVisible(show);
    }
    public boolean getShowNavigation() { return this.showNavigation; }

    // add a new file to this panel
    public void addFile (File f) {
        Arquivo arquivo = new Arquivo(f);
        arquivo.setParent(this);
        arquivo.setVisible(true);

        panFiles.add(arquivo);
    }

    // clean this panel
    public void clear () {
        setVisible(false);
        panFiles.removeAll();
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrScrollBar = new javax.swing.JScrollPane();
        panFiles = new javax.swing.JPanel();
        btnIr = new javax.swing.JButton();
        txtPath = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();

        scrScrollBar.setName("scrScrollBar"); // NOI18N

        panFiles.setName("panFiles"); // NOI18N
        panFiles.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        scrScrollBar.setViewportView(panFiles);

        btnIr.setText("Ir");
        btnIr.setName("btnIr"); // NOI18N
        btnIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrActionPerformed(evt);
            }
        });

        txtPath.setName("txtPath"); // NOI18N

        btnVoltar.setText("Voltar");
        btnVoltar.setName("btnVoltar"); // NOI18N
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPath, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIr))
            .addComponent(scrScrollBar, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnIr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrScrollBar, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrActionPerformed
        loadPath(txtPath.getText());
}//GEN-LAST:event_btnIrActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        File arquivo = new File(txtPath.getText());
        String pai = arquivo.getParent();
        if (pai != null) {
            loadPath(pai);
            txtPath.setText(pai);
        }
}//GEN-LAST:event_btnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIr;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel panFiles;
    private javax.swing.JScrollPane scrScrollBar;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables

    // adiciona os arquivos a partir de um caminho
    void loadPath(String path) {
        clear();

        setVisible(false);
        
        txtPath.setText(new File(path).getAbsolutePath());

        File aqui = new File(path);
        File[] arquivos = aqui.listFiles();
        if (arquivos != null)
            for (int i = 0; i < arquivos.length; i++)
                addFile(arquivos[i]);

        setVisible(true);
    }

}
